package com.example.bizcardcomposecourse.model

data class Movie(
    val title: String,
    val year: String,
    val rated: String? = null,
    val released: String? = null,
    val runtime: String? = null,
    val genre: String? = null,
    val director: String? = null,
    val writer: String? = null,
    val actors: String? = null,
    val plot: String? = null,
    val language: String? = null,
    val country: String? = null,
    val awards: String? = null,
    val poster: String? = null,
    val metaScore: String? = null,
    val imdbRating: String? = null,
    val imdbVotes: String? = null,
    val imdbID: String? = null,
    val type: String? = null,
    val totalSeasons: String? = null,
    val response: String,
    val images: List<String>
)

fun getMovies() = listOf(
    Movie(
        title = "Avatar",
        year = "2009",
        rated = "PG-13",
        released = "18 Dec 2009",
        runtime = "162 min",
        genre = "Action, Adventure, Fantasy",
        director = "James Cameron",
        writer = "James Cameron",
        actors = "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
        plot = "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
        language = "English, Spanish",
        country = "USA, UK",
        awards = "Won 3 Oscars. Another 80 wins & 121 nominations.",
        poster = "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
        metaScore = "83",
        imdbRating = "7.9",
        imdbVotes = "890,617",
        imdbID = "tt0499549",
        type = "movie",
        response = "True",
        images = listOf(
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyOTYyMzUxNl5BMl5BanBnXkFtZTcwNTg0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
            "https://images-na.ssl-images-amazon.com/images/M/MV5BNzM2MDk3MTcyMV5BMl5BanBnXkFtZTcwNjg0MTUzNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY2ODQ3NjMyMl5BMl5BanBnXkFtZTcwODg0MTUzNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxOTEwNDcxN15BMl5BanBnXkFtZTcwOTg0MTUzNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYxMDg1Nzk1MV5BMl5BanBnXkFtZTcwMDk0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg"
        )
    ),
    Movie(
        title = "I Am Legend",
        year = "2007",
        rated = "PG-13",
        released = "14 Dec 2007",
        runtime = "101 min",
        genre = "Drama, Horror, Sci-Fi",
        director = "Francis Lawrence",
        writer = "Mark Protosevich (screenplay), Akiva Goldsman (screenplay), Richard Matheson (novel), John William Corrington, Joyce Hooper Corrington",
        actors = "Will Smith, Alice Braga, Charlie Tahan, Salli Richardson-Whitfield",
        plot = "Years after a plague kills most of humanity and transforms the rest into monsters, the sole survivor in New York City struggles valiantly to find a cure.",
        language = "English",
        country = "USA",
        awards = "9 wins & 21 nominations.",
        poster = "http://ia.media-imdb.com/images/M/MV5BMTU4NzMyNDk1OV5BMl5BanBnXkFtZTcwOTEwMzU1MQ@@._V1_SX300.jpg",
        metaScore = "65",
        imdbRating = "7.2",
        imdbVotes = "533,874",
        imdbID = "tt0480249",
        type = "movie",
        response = "True",
        images = listOf(
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMTI0NTI4NjE3NV5BMl5BanBnXkFtZTYwMDA0Nzc4._V1_.jpg",
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMTIwMDg2MDU4M15BMl5BanBnXkFtZTYwMTA0Nzc4._V1_.jpg",
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc5MDM1OTU5OV5BMl5BanBnXkFtZTYwMjA0Nzc4._V1_.jpg",
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMTA0MTI2NjMzMzFeQTJeQWpwZ15BbWU2MDMwNDc3OA@@._V1_.jpg"
        )
    ),
    Movie(
        title = "300",
        year = "2006",
        rated = "R",
        released = "09 Mar 2007",
        runtime = "117 min",
        genre = "Action, Drama, Fantasy",
        director = "Zack Snyder",
        writer = "Zack Snyder (graphic novel), Kurt Johnstad (screenplay), Michael Gordon (screenplay), Frank Miller (graphic novel), Lynn Varley (graphic novel)",
        actors = "Gerard Butler, Lena Headey, Dominic West, David Wenham",
        plot = "King Leonidas of Sparta and a force of 300 men fight the Persians at Thermopylae in 480 B.C.",
        language = "English",
        country = "USA",
        awards = "16 wins & 42 nominations.",
        poster = "http://ia.media-imdb.com/images/M/MV5BMTYxNTU4NzY3MV5BMl5BanBnXkFtZTcwMjI2MTIyMw@@._V1_SX300.jpg",
        metaScore = "52",
        imdbRating = "7.7",
        imdbVotes = "611,046",
        imdbID = "tt0416449",
        type = "movie",
        response = "True",
        images = listOf(
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4NTc4MzYzNF5BMl5BanBnXkFtZTcwNTkzNzAzMw@@._V1_.jpg",
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc4NTAxNzQ3Nl5BMl5BanBnXkFtZTcwNzUzNzAzMw@@._V1_.jpg",
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk2OTgyMjkzNl5BMl5BanBnXkFtZTcwNjUzNzAzMw@@._V1_.jpg"
        )
    ),
    Movie(
        title = "The Avengers",
        year = "2012",
        rated = "PG-13",
        released = "04 May 2012",
        runtime = "143 min",
        genre = "Action, Sci-Fi, Thriller",
        director = "Joss Whedon",
        writer = "Joss Whedon (screenplay), Zak Penn (story)",
        actors = "Robert Downey Jr., Chris Evans, Scarlett Johansson, Samuel L. Jackson",
        plot = "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
        language = "English, Russian, Hindi",
        country = "USA",
        awards = "Nominated for 1 Oscar. Another 34 wins & 75 nominations.",
        poster = "http://ia.media-imdb.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThhYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        metaScore = "69",
        imdbRating = "8.1",
        imdbVotes = "1,005,299",
        imdbID = "tt0848228",
        type = "movie",
        response = "True",
        images = listOf(
            "https://images-na.ssl-images-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThhYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk3OTc3NzI1OF5BMl5BanBnXkFtZTcwNzUzNzAzMw@@._V1_.jpg",
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ2NzQ0MDkxMV5BMl5BanBnXkFtZTcwNTU3NzAzMw@@._V1_.jpg",
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU5MTE2ODc0NV5BMl5BanBnXkFtZTcwNjU3NzAzMw@@._V1_.jpg"
        )
    ),
    Movie(
        title = "The Wolf of Wall Street",
        year = "2013",
        rated = "R",
        released = "25 Dec 2013",
        runtime = "180 min",
        genre = "Biography, Crime, Drama",
        director = "Martin Scorsese",
        writer = "Terence Winter (screenplay), Jordan Belfort (book)",
        actors = "Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey",
        plot = "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
        language = "English, French",
        country = "USA",
        awards = "Nominated for 5 Oscars. Another 35 wins & 104 nominations.",
        poster = "http://ia.media-imdb.com/images/M/MV5BMjAxMzY3NjcxN15BMl5BanBnXkFtZTcwNTc5MTUwMw@@._V1_SX300.jpg",
        metaScore = "75",
        imdbRating = "8.2",
        imdbVotes = "533,493",
        imdbID = "tt0993846",
        type = "movie",
        response = "True",
        images = listOf(
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMjAxMzY3NjcxN15BMl5BanBnXkFtZTcwNTc5MTUwMw@@._V1_SX300.jpg",
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM2NTI3NDc5Nl5BMl5BanBnXkFtZTgwOTg2NjIzMDE@._V1_.jpg",
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkxNjAxNjAxNV5BMl5BanBnXkFtZTgwOTg3NjIzMDE@._V1_.jpg",
            "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY3OTU4Njg0MV5BMl5BanBnXkFtZTgwOTg4NjIzMDE@._V1_.jpg"
        )
    )
)

